# Generated by Django 2.2.17 on 2020-12-30 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NOM', models.TextField()),
                ('PRENOM', models.TextField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('NUM', models.TextField()),
                ('ANNUAIRE', models.IntegerField()),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
