# Generated by Django 2.2.17 on 2021-01-18 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NOM', models.CharField(max_length=20)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NOM', models.CharField(max_length=30)),
                ('PRENOM', models.CharField(max_length=20)),
                ('EMAIL', models.EmailField(max_length=50)),
                ('NUM', models.CharField(max_length=20)),
                ('ANNUAIRE', models.IntegerField()),
                ('GROUPE', models.CharField(max_length=20)),
                ('STATUT', models.CharField(max_length=20)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ANNEE', models.IntegerField()),
                ('FILIERE', models.CharField(max_length=20)),
                ('NOM', models.CharField(max_length=20)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
