# Generated by Django 2.2.17 on 2021-01-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individu',
            name='GROUPE',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='STATUT',
        ),
    ]
