# Generated by Django 2.2.17 on 2021-01-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0002_auto_20210118_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='GROUPE',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='individu',
            name='STATUT',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
