# Generated by Django 2.2.17 on 2021-01-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0003_auto_20210118_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='NUM',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
