# Generated by Django 2.2.17 on 2021-02-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individu', '0004_auto_20210119_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individu',
            name='STATUT',
        ),
    ]
